### ISSUE TITLE
python NameError on latest release

### ISSUE THREAD

**Issue by eptru** [fayaz12g/aar-launcher#4]
First of all thank you for developing this tool and keep maintaining it, very helpful!

I am running into a python NameError when trying to generate the mod using the latest release Fayaz's Settings 2.0.4. 
I tried to install the dependency package via `pip install keystone-engine` but still same error.

```
8.0.3
invalid command name "2574613463872update"
    while executing
"2574613463872update"
    ("after" script)
invalid command name "2574613473728check_dpi_scaling"
    while executing
"2574613473728check_dpi_scaling"
    ("after" script)
invalid command name "2574613438720_click_animation"
    while executing
"2574613438720_click_animation"
    ("after" script)
Exception in thread Thread-1 (select_mario_folder):
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "C:\Users\jaewk\AppData\Roaming\AnyAspectRatio\eow-aar-main\GUI.py", line 344, in select_mario_folder
    create_patch_files(patch_folder, str(ratio_value), str(scaling_factor), visual_fixes)
  File "C:\Users\jaewk\AppData\Roaming\AnyAspectRatio\eow-aar-main\patch.py", line 12, in create_patch_files
    hex_value1, hex_value2= eow_hex23(ratio_value)
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaewk\AppData\Roaming\AnyAspectRatio\eow-aar-main\functions.py", line 106, in eow_hex23
    hex_value1 = asm_to_hex(asm_1)
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\jaewk\AppData\Roaming\AnyAspectRatio\eow-aar-main\functions.py", line 94, in asm_to_hex
    ks = Ks(KS_ARCH_ARM64, KS_MODE_LITTLE_ENDIAN)
         ^^
NameError: name 'Ks' is not defined. Did you mean: 'ks'?
```

**Comment by fayaz12g** [comment]
Hi. Unfortunately because of Nintendo's constant DMCAs and lawsuits, I've put this project on an indefinite hold out of fear of attracting their attention. You may have some success using an older version, but otherwise I can't offer assistance. I'm sorry.
